name: "nuget publish"

on:
  workflow_dispatch:
    inputs:
      tags:
        description: '版本号'
        required: true
        default: ''

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make executeable
      run: chmod +x ./.github/scripts/nuget-publish.sh
    - name: Nuget Publish
      run:  ./.github/scripts/nuget-publish.sh ${{github.event.inputs.tags}} ${{secrets.NUGET_PASSWORD}}
      shell: bash